export const storyContent = {
  landing: {
    title: "Konni Journeys Scroll Cheyyalem.",
    subtitle: "Unlock Cheyyali.",
    subtext: "Ee story chadavadaniki permission kaadhu…\nIntent undali.",
    cta: "Connect Wallet to Enter"
  },
  sections: [
    {
      id: "introduction",
      title: "🌱 Where do I even start?",
      content: [
        "\"Oka message valla naa life lo entha impact untundhaa?\"",
        "Yes. Untundhi. Chala untundhi.",
        "",
        "Idhi oka birthday message kaadhu.",
        "Idhi naa life lo jarigina change gurinchi.",
        "Idhi naa journey gurinchi.",
        "Idhi mee valla nenu ela ayipoyaano cheppe oka honest expression.",
        "",
        "Where do I even start, bro?",
        "",
        "Oka message valla naa life lo entha impact untundhaa?",
        "Yes. Untundhi. Chala untundhi.",
        "",
        "But idhi naa life lo jarigina motham change gurinchi.",
        "",
      ],
      image: "/images/image1.jpg"
    },
    {
      id: "first-year",
      title: "🌱 First year – fear, admiration, distance",
      content: [
        "Nenu 1st year lo unnapudu,",
        "Aprameya Community group lo \"Designing ki interested unna vallu DM cheyandi\" ani message vachindhi.",
        "",
        "Sarle ani Praveen ki Text chesa naaku video editing ochu ani ",
        "",
        "Editing proper gaa raadhu.",
        "\"Kaliste expose ayipotha, nannu theskooru le\" ani bhayam.",
        "",
        "So mellaga nene side ayipoyaa.",
        "",
        "But nijam cheppalante —",
        "naa 1st year motham Aprameya club okkate follow aye vadni",
        "",
        "Enni sarlu Aprameya community channel open chesi mee profiles chusano naake thelidhu.",
        "Mee DP lu chusi",
        "\"Ee annai ye nenu matladindhi\" ani anukovatam.",
        "",
        "#hashinclude time lo mee events ki ravatam.",
        "",
        "Appatlo meeru naaku aakasallo unde vallu bro.",
        "\"Ee annailu full toppers. Club petti maintain chesthunnaru\" ani.",
        "",
        "SIL events lo konni self elevations vintunte —",
        "\"Baboi… ee annailu mamulu ollu kaadhu\" ani hype penchukune vadni.",
        "",
        "Sundar anna maa friends ki doubts clear chesthunte,",
        "\"Asalu ee annailu errors anni ela solve chesthunnaru ra?\" ani anukune vadni.",
        "",
        "1st year lo meeru naaku HIGH LEVEL people bro. 😭"
      ]
    },
    {
      id: "club-announcement",
      title: "🔁 Club announcement & unexpected turn",
      content: [
        "2nd year loo",
        "Tarvatha nuvvu Aprameya lo club announce chesinappudu,",
        "\"Orini… veelu mamulu ollu kaadhu ra\" ani anukunna.",
        "",
        "But real turning point entante —",
        "oka roju nuvvu naaku message pettav:",
        "",
        "\"Editing chesthunava ra?\"",
        "",
        "Asalu adhi naa life lo major turning point.",
        "",
        "Naaku ardham kaaledhu bro —",
        "\"Neeku nenu ela gurthunta?\"",
        "\"Just 2 times chat chesam kadha?\"",
        "",
        "Sarle… 2-1 ki ocham…",
        "club lo undam…",
        "koncham badai kottudam…",
        "SIL points padathayi ani join ayyaa."
      ],
      isHighlight: true
    },
    {
      id: "recruitments",
      title: "🎥 Recruitments, ",
      content: [
        "Recruitments time lo Devara movie book cheskunna anna ani cheppa..…",
        "\"Interview emundhi le ra, direct attack nuvvu\" ani nuvvu cheppadam…",
        "",
        "Naa position nene adagatam.",
        "Works thakkuva untayi emo ani non tech lead adiga",
        "adigina ventane sare nuvve non tech lead ani aneyatam",
        "jagrathaga anni works proper gaa cheyyatam.",
        "",
        "Naaku pedda position icharuu ani",
        "\"jagrathaga undali\" ani pressure tho work cheyyatam.",
        "",
        "Everything slowly started happening."
      ],
      image: "/images/image2.jpg"
    },
    {
      id: "from-seniors",
      title: "🤍 From seniors to something more",
      content: [
        "2-1 lo classes bunk kotti library ki vellinappudu,",
        "meeru kanipinchadam.",
        "Mee pakkana kurchopettukovadam.",
        "",
        "Asalu entha easy gaa, entha fast gaa meetho kalisipoyaano —",
        "asalu chala close ayipoya meeeku",
        "adhi naa life lo best part.",
        "",
        "2-2 ayithe em cheppali bro?",
        "",
        "Meeru lekunda naa day start avvadam kashtam ayipoyindhi.",
        "",
        "Bunks.",
        "Kalavatam.",
        "C123 moments.",
        "Navvulu.",
        "Stress share cheskovadam.",
        "",
        "NAAC week ayithe vere level enjoymentt asaluu",
        "",
        "Meeru one week Bangalore vellinappudu —",
        "aa week asaluu undaleka poyaa bro.",
        "That much addicted."
      ],
      image: "/images/image3.jpg"
    },
    {
      id: "club-impact",
      title: "🏆 Club valla naa life maarindhi",
      content: [
        "Club valla naaku chala ochai bro life lo.",
        "",
        "Respect.",
        "Existence.",
        "Identity.",
        "",
        "Faculty parichayalu —",
        "entha mandhini paricheyam chesaro meeru.",
        "",
        "Monna evado cheppadu:",
        "",
        "\"Bro nuvvu TBH President kadha… aa roju alaga help chesav, thanks.\"",
        "",
        "Asalu aa respect naaku osthundhi ante —",
        "reason nuvve bro. 😭❤️",
        "",
        "Neeku chala connections unnai maa batch loo",
        "naake club responsibility ichav.",
        "",
        "No matter what —",
        "one day ninnu, club ni proud feel ayyela chestha."
      ],
      image: "/images/image4.jpg"
    },
    {
      id: "blockchain",
      title: "🔗 Blockchain – naa life direction",
      content: [
        "Academics lo kuda nuvvu naaku chala chesav bro.",
        "",
        "Naaku clarity lekunda, path lekunda unna time lo —",
        "Blockchain ni naa life laaga chesesav.",
        "",
        "Specialization confusion lo —",
        "balavantham gaa Blockchain pettinchav.",
        "",
        "Zero friends in blockchain.",
        "Zero idea.",
        "",
        "Ivvala —",
        "Blockchain naa identity ayipoyindhi.",
        "",
        "maa class loone nenu class cheppatam",
        "class unappudu alla Faculty pakkana kurchoni matladatam.",
        "Section motham different gaa choodadam.",
        "",
        "Ee highs anni —",
        "aa oka decision valle."
      ]
    },
    {
      id: "more-than-senior",
      title: "🧠 More than a senior",
      content: [
        "From",
        "Anna → Praveen → Orey → Kojja",
        "ee journey unpredictable bro. 🥵",
        "",
        "Naa B.Tech life lo",
        "\"Oka person \" ante —",
        "adhi nuvve.",
        "",
        "Naa OG.",
        "Naa Salaar.",
        "Naa Mentor",
        "emani cheppaali brooo"
      ]
    },
    {
      id: "gratitude",
      title: "🙏 Gratitude that won't fade",
      content: [
        "HODs tho, HKV sir tho,",
        "bhayam lekunda matladadam —",
        "adhi kuda nuvvu nerpinchav.",
        "",
        "\"Mana club undhi gaa\"",
        "ani faculty cheppinappudu",
        "naaku ardham ayindhi —",
        "I've grown ani",
        "",
        "Ee club naaku jeevitham ichindhi bro.",
        "Nenu runa padi untanu —",
        "neeeku, ee club ki.",
        "",
        "Break teeskunna kuda,",
        "juniors ki support gaa untanu.",
        "",
        "Because —",
        "ee phase naa life lo forever untundhi."
      ]
    },
    {
      id: "final-truth",
      title: "🖤 Final truth",
      content: [
        "Idhi celebration kaadhu.",
        "Idhi formality kaadhu.",
        "Idhi over-expression kaadhu.",
        "",
        "Idhi naa heart lo unna truth.",
        "",
        "Future lo em jarigina,",
        "nenu win ayina, fail ayina —",
        "",
        "ee moments maatram",
        "naa life antha untayi."
      ]
    }
  ]
}
